// <auto-generated />
using FeatureJuan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureJuan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311124702_create_tables")]
    partial class create_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureJuan.Models.Divisao", b =>
                {
                    b.Property<int>("DivisaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisaoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisaoId");

                    b.ToTable("Divisoes");

                    b.HasData(
                        new
                        {
                            DivisaoId = 1,
                            Nome = "Brasileirão Série A"
                        },
                        new
                        {
                            DivisaoId = 2,
                            Nome = "Brasileirão Série B"
                        },
                        new
                        {
                            DivisaoId = 3,
                            Nome = "La Liga"
                        },
                        new
                        {
                            DivisaoId = 4,
                            Nome = "Premier League"
                        },
                        new
                        {
                            DivisaoId = 5,
                            Nome = "Ligue 1"
                        });
                });

            modelBuilder.Entity("FeatureJuan.Models.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"));

                    b.Property<int>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeIntegrantes")
                        .HasColumnType("int");

                    b.HasKey("EquipeId");

                    b.HasIndex("DivisaoId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("FeatureJuan.Models.Equipe", b =>
                {
                    b.HasOne("FeatureJuan.Models.Divisao", "Divisao")
                        .WithMany("Equipes")
                        .HasForeignKey("DivisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisao");
                });

            modelBuilder.Entity("FeatureJuan.Models.Divisao", b =>
                {
                    b.Navigation("Equipes");
                });
#pragma warning restore 612, 618
        }
    }
}
