// <auto-generated />
using FeatureJuan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeatureJuan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FeatureJuan.Models.Divisao", b =>
                {
                    b.Property<string>("DivisaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisaoId");

                    b.ToTable("Divisoes");

                    b.HasData(
                        new
                        {
                            DivisaoId = "1",
                            Nome = "Brasileirão Série A"
                        },
                        new
                        {
                            DivisaoId = "2",
                            Nome = "Brasileirão Série B"
                        },
                        new
                        {
                            DivisaoId = "3",
                            Nome = "La Liga"
                        },
                        new
                        {
                            DivisaoId = "4",
                            Nome = "Premier League"
                        },
                        new
                        {
                            DivisaoId = "5",
                            Nome = "Ligue 1"
                        });
                });

            modelBuilder.Entity("FeatureJuan.Models.Equipe", b =>
                {
                    b.Property<string>("EquipeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DivisaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantidadeIntegrantes")
                        .HasColumnType("int");

                    b.HasKey("EquipeId");

                    b.HasIndex("DivisaoId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("FeatureJuan.Models.Equipe", b =>
                {
                    b.HasOne("FeatureJuan.Models.Divisao", "Divisao")
                        .WithMany()
                        .HasForeignKey("DivisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisao");
                });
#pragma warning restore 612, 618
        }
    }
}
